#Generated by VisualGDB (http://visualgdb.com)
#DO NOT EDIT THIS FILE MANUALLY UNLESS YOU ABSOLUTELY NEED TO
#USE VISUALGDB PROJECT PROPERTIES DIALOG INSTEAD

BINARYDIR := Debug

#Additional flags
PREPROCESSOR_MACROS := DEBUG=1 USE_STM32F4XX_NUCLEO STM32F411xE OSXMOTIONFX_STORE_CALIB_FLASH STSPIN_240
INCLUDE_DIRS := src src/imu src/motor ../../../../../../../STM32/X-CUBE-MEMS1/Drivers/BSP/Components/Common ../../../../../../../STM32/X-CUBE-MEMS1/Drivers/BSP/Components/hts221 ../../../../../../../STM32/X-CUBE-MEMS1/Drivers/BSP/Components/lis3mdl ../../../../../../../STM32/X-CUBE-MEMS1/Drivers/BSP/Components/lps22hb ../../../../../../../STM32/X-CUBE-MEMS1/Drivers/BSP/Components/lps25hb ../../../../../../../STM32/X-CUBE-MEMS1/Drivers/BSP/Components/lsm6ds0 ../../../../../../../STM32/X-CUBE-MEMS1/Drivers/BSP/Components/lsm6ds3 ../../../../../../../STM32/X-CUBE-MEMS1/Drivers/BSP/X_NUCLEO_IKS01A1 ../../../../../../../STM32/X-CUBE-MEMS1/Drivers/BSP/STM32F4xx-Nucleo ../../../../../../../STM32/X-CUBE-MEMS1/Middlewares/ST/STM32_OSX_MotionFX_Library ../../../../../../../STM32/X-CUBE-MEMS1/Middlewares/ST/STM32_OSX_MotionFX_Library/Inc ../../../../../../../STM32/X-CUBE-WIFI1/Middlewares/ST/STM32_SPWF01SA/Inc ../../../../../../../STM32/X-CUBE-WIFI1/Middlewares/ST/STM32_SPWF01SA/Utils ../../../../../../../STM32/X-CUBE-WIFI1/Middlewares/ST/STM32_SPWF01SA ../../../../../../../STM32/X-CUBE-WIFI1/Drivers/BSP/X-NUCLEO-IDW01M1 src/math src/Controller src/PID src/wifi src/wifi/ESP8266Interface src/wifi/ESP8266Interface/ESP8266 src/wifi/ESP8266Interface/Helper src/wifi/ESP8266Interface/Socket src/motor/X-NUCLEO-IHM12A1/Components/Common src/motor/X-NUCLEO-IHM12A1/Components/stspin240_250 src/motor/X-NUCLEO-IHM12A1/ST_INTERFACES/Actuators src/motor/X-NUCLEO-IHM12A1/ST_INTERFACES/Common src/motor/X-NUCLEO-IHM12A1
LIBRARY_DIRS := ../../../../../../../STM32/X-CUBE-MEMS1/Middlewares/ST/STM32_OSX_MotionFX_Library/Lib
LIBRARY_NAMES := osxMotionFX107_CM4_GCC_ot
ADDITIONAL_LINKER_INPUTS := 
MACOS_FRAMEWORKS := 
LINUX_PACKAGES := 

CFLAGS := -ggdb -ffunction-sections -O0
CXXFLAGS := -ggdb -ffunction-sections -fno-exceptions -fno-rtti -O0
ASFLAGS := 
LDFLAGS := -Wl,-gc-sections
COMMONFLAGS := 
LINKER_SCRIPT := 

START_GROUP := 
END_GROUP := 

#Additional options detected from testing the toolchain
USE_DEL_TO_CLEAN := 1
CP_NOT_AVAILABLE := 1

ADDITIONAL_MAKE_FILES := mbed.mak
GENERATE_BIN_FILE := 1
GENERATE_IHEX_FILE := 0
